default_platform(:android)

platform :android do
   desc "Assemble source"
    lane :assemble do
        gradle(task: "assembleRelease")
    end
    lane :upload do
        testfairy(
          api_key: ENV["TESTFAIRY_API_KEY"],
          apk: "../build/app/outputs/flutter-apk/app-release.apk",
          comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
        )
    end
end