name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
#  github-action-android:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#      - name: Flutter Action
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '2.5.3'
#      - name: Flutter Pub Get
#        run: flutter pub get
#      - name: Flutter Pub Test
#        run: flutter test
#      - name: Make APK
#        run: flutter build apk
#      - name: Make testfairy executable
#        run: chmod +x ./testfairy-uploader.sh
#      - name: Moving APK to TestFairy
#        run: ./testfairy-uploader.sh build/app/outputs/flutter-apk/app-release.apk

  github-action-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Flutter Action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Flutter Pub Test
        run: flutter test
      - name: Build IOS
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving APK to TestFairy
        run: |
          exec ./testfairy-uploader.sh build/ios/iphoneos/app.ipa