name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17.0.2+8
          distribution: temurin
      - name: Flutter Action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Flutter Pub Test
        run: flutter test
      - name: Make APK
        run: flutter build apk
