name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  github-action-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Flutter Action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Flutter Pub Test
        run: flutter test
      - name: Make APK
        run: flutter build apk --release
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving APK to TestFairy
        run: ./testfairy-uploader.sh build/app/outputs/flutter-apk/app-release.apk ${{ secrets.TESTFAIRY_API_KEY }}

#  fastlane-android:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#      - name: Flutter Action
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '2.5.3'
#      - name: Flutter Pub Get
#        run: flutter pub get
#      - name: Set up Ruby 2.6
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: 2.6.x
#      - name: Install Dependencies
#        run: gem install bundler && bundle install
#      - name: Make gradlew executable
#        run: chmod +x /home/runner/work/demo/demo/gradlew
#      - name: Run Fastlane Assemble Lane
#        run: fastlane assemble
#      - name: Make testfairy executable
#        run: chmod +x ./testfairy-uploader.sh
#      - name: Moving APK to TestFairy
#        run: ./testfairy-uploader.sh build/app/outputs/flutter-apk/app-release.apk ${{ secrets.TESTFAIRY_API_KEY }}

  github-action-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Flutter Action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Flutter Pub Test
        run: flutter test
      - name: Build IOS
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s /Users/runner/work/flutter_cicd/flutter_cicd/build/ios/iphoneos/Runner.app
          cd ..
          zip -r app.ipa Payload
          echo pwd
          ls
          cd ./
          ls
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving IPA to TestFairy
        run: |
          exec ./testfairy-uploader.sh Users/runner/work/flutter_cicd/flutter_cicd/build/ios/iphoneos/app.ipa ${{ secrets.TESTFAIRY_API_KEY }}